{
 "title": "Podman Dashboard",
 "description": "Podman dashboard original by DreamOfIce, modify by tico88612",
 "tags": [ "podman" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "PodmanExporter",
    "label": "Host",
    "query": {
     "query": "label_values(podman_container_info,instance)"
    }
   },
   {
    "name": "NodeExporter",
    "query": {
     "query": "label_values(node_arp_entries,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "podman_container_info", "legendFormat": "基本信息" },
    { "expr": "podman_container_state", "legendFormat": "状态" },
    {
     "expr": "podman_container_mem_usage_bytes",
     "legendFormat": "__auto"
    },
    { "expr": "podman_container_exit_code", "legendFormat": "__auto" },
    {
     "expr": "time() - podman_container_started_seconds",
     "legendFormat": "__auto"
    },
    { "expr": "podman_container_pids", "legendFormat": "__auto" },
    {
     "expr": "podman_container_mem_usage_bytes / (podman_container_mem_limit_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Container Details(Host: $PodmanExporter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Total CPU of containers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(podman_container_cpu_seconds_total{instance=~\"$PodmanExporter\"}[$__rate_interval])) / count(node_cpu_seconds_total{instance=~\"$NodeExporter\",mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(podman_container_cpu_seconds_total{instance=~\"$PodmanExporter\"}[$__rate_interval]) / 60",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "podman_container_mem_usage_bytes{instance=~\"$PodmanExporter\"}",
     "legendFormat": "{{id}}_current"
    },
    {
     "expr": "podman_container_mem_limit_bytes{instance=~\"$PodmanExporter\"}",
     "legendFormat": "{{id}}_max"
    }
   ]
  },
  {
   "title": "Total memory of containers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podman_container_mem_usage_bytes{instance=~\"$PodmanExporter\"}) / sum(node_memory_MemTotal_bytes{instance=~\"$NodeExporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(podman_container_block_input_total{instance=\"$PodmanExporter\"}[$__rate_interval])",
     "legendFormat": "{{id}}_in"
    },
    {
     "expr": "increase(podman_container_block_output_total{instance=\"$PodmanExporter\"}[$__rate_interval])",
     "legendFormat": "{{id}}_out"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "increase(podman_container_net_input_total{instance=\"$PodmanExporter\"}[$__rate_interval]) * 8",
     "legendFormat": "{{id}}_in"
    },
    {
     "expr": "increase(podman_container_net_output_total{instance=\"$PodmanExporter\"}[$__rate_interval]) * 8",
     "legendFormat": "{{id}}_out"
    }
   ]
  },
  {
   "title": "Image Details(Host: $PodmanExporter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Total Image Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podman_image_size{instance=~\"$PodmanExporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podman_image_size{instance=~\"$PodmanExporter\"}) / sum(node_filesystem_size_bytes{instance=~\"$NodeExporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "podman_image_info{instance=\"$PodmanExporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "podman_image_created_seconds{instance=\"$PodmanExporter\"} * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "podman_image_size{instance=\"$PodmanExporter\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}