global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'discord' 
  routes:
  - match:
      severity: critical 
    receiver: discord
  # - match_re: # regular expression
  #     severity: ^(warning|critical)$
  #   receiver: telegram

receivers:
  - name: 'discord'
    webhook_configs:
    - url: 'http://alertmanager-discord:9094'
  # - name: 'telegram'
  #   telegram_config:
  #   - bot_token: ''
  #   - chat_id: ''

inhibit_rules: []
