apiVersion: v1
kind: Pod
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  containers:
  - image: docker.io/prom/prometheus:v2.44.0
    name: prometheus
    ports:
    - containerPort: 9090
      hostPort: 9090
    securityContext: {}
    volumeMounts:
    - mountPath: /etc/prometheus
      name: config-volume
    - mountPath: /prometheus
      name: prom-data-pvc
  volumes:
  - name: config-volume
    configMap:
      name: prometheus-config
  - name: prom-data-pvc
    persistentVolumeClaim:
      claimName: prom-data
