apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/driver: local
  name: prom-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5G
