apiVersion: v1
kind: Pod
metadata:
  labels:
    app: alertmanager
  name: alertmanager
spec:
  containers:
  - image: quay.io/prometheus/alertmanager:v0.25.0
    name: alertmanager
    ports:
    - containerPort: 9093
    volumeMounts:
    - mountPath: /etc/alertmanager
      name: config-volume
    - mountPath: /alertmanager
      name: am-data-pvc
  volumes:
  - name: config-volume
    configMap:
      name: alertmanager-config
  - name: am-data-pvc
    persistentVolumeClaim:
      claimName: am-data