apiVersion: v1
kind: Pod
metadata:
  labels:
    app: node-exporter
  name: node-exporter
spec:
  containers:
  - args:
    - --path.rootfs=/host
    image: quay.io/prometheus/node-exporter:v1.6.1
    name: node-exporter
    ports:
    - containerPort: 9100
    securityContext: {}
    volumeMounts:
    - mountPath: /host
      name: root-host
      readOnly: true
  volumes:
  - hostPath:
      path: /
      type: Directory
    name: root-host
